version: '3.7'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PORT=5432
      - DB_HOST=db
      - REDIS_HOST=redis
      - REDIS_PORT=6379

    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:14.0
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    ports:
      - ${DB_EXTERNAL_PORT}:3306

networks:
  backend:
